obj-y += main.o

obj-y += core/event.o
obj-y += core/queue.o

obj-y += detect/detector.o
obj-y += detect/process.o
obj-y += detect/syscall.o
obj-y += detect/module.o
obj-y += detect/memory.o
obj-y += detect/integrity.o

obj-y += scan/scanner.o
obj-y += scan/process.o
obj-y += scan/memory.o
obj-y += scan/module.o
obj-y += scan/file.o
obj-y += scan/network.o

obj-y += policy/policy.o
obj-y += response/neutralizer.o
obj-y += security/secure.o
obj-y += reporting/informator.o
