# Phantom OSD

obj-y += phantomsysinfo.o
obj-y += phantom_syscalls.o

obj-y += osd.o
obj-y += osd_window.o
obj-y += osd_manager.o
obj-y += osd_desktop.o
obj-y += osd_render.o
obj-y += phantom_osd_device.o
